networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:8
    container_name: chat_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "chatuser", "--password=chatpassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: chat_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: chatuser
      DB_PASSWORD: chatpassword
      DB_NAME: chatdb
      JWT_SECRET: your_jwt_secret
      PORT: 3000
      DB_MAX_RETRIES: 5
      DB_RETRY_INTERVAL: 5000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: chat_frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: http://localhost:3000/api
    networks:
      - app-network

volumes:
  mysql_data:
