version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: chat_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: chat_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: chatuser
      DB_PASSWORD: chatpassword
      DB_NAME: chatdb
      JWT_SECRET: your_jwt_secret
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: chat_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:80"
    environment:
      REACT_APP_API_URL: http://localhost:80

volumes:
  mysql_data:
